services:
  evobot:
    container_name: evobot
    restart: unless-stopped
    image: navystack/evobot
    #volumes:
    #  - ./config.json:/home/evobot/dist/config.json
    networks:
      - internal
    #environment:
    #  - 'DISCORD_TOKEN=some-important-key'
networks: 
  internal:
